---
- name: smoke test
  block:
  - name: curl {{ smoke_test_haproxy_vip }}
    ansible.builtin.command:
      cmd: curl "{{ smoke_test_haproxy_vip }}"
    register: result
  - name: debug
    ansible.builtin.debug:
      msg: "{{ result.stdout_lines }}"

